[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
quinn = "0.11"
quinn-proto = "0.11"
bytes = "1.10"
rustls = "0.23"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
