[package]
name = "client_bevy"
version = "0.0.0"
edition = "2024"

[dependencies]
bevy = "0.15"
bevy_async_task = "0.4"

url = "2.5"
web-transport = { git = "https://github.com/kixelated/web-transport-rs" }

[lints]
workspace = true
