[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = {  version = "1.0", features = ["net", "os-poll"] }
quinn-proto = "0.11"
bytes = "1.10"
rustls = "0.23"
rcgen = "0.13"
